### ISSUE TITLE
Misleading quickstart flow on graph.cool

### ISSUE THREAD

**Issue by sedubois** [graphcool/graphcool-framework#1]
For **bug reports**, please fill in the next sections:

**Current behavior**

The first step of the visitor onboarding seems broken because of a confusion between `graphcool` and `graphcool-framework`, so I don't know how to proceed (I consider myself a visitor because I haven't coded with Graphcool in several months and was hoping that the website would get me up to speed again).

**Reproduction**

- visit www.graph.cool: it instructs to do `npm i -g graphcool-framework`
- click on the "get started" button: it leads to a page which instructs to do `npm i -g graphcool`. So which one is it?

<img width="1206" alt="gc_1" src="https://user-images.githubusercontent.com/4217871/35101199-56831e10-fc67-11e7-83d1-cfade2e461ad.png">
<img width="1170" alt="gc_2" src="https://user-images.githubusercontent.com/4217871/35101200-56a7d0de-fc67-11e7-9911-ab5f28c6d079.png">

**Expected behavior?**

Ideally there should be one integrated way to manage grapcool instead of multiple binaries, and at the very least the different documentation pages shouldn't contradict each other, especially when onboarding visitors. 

It also led me to the question of whether there are still any plans to actively develop the graphcool-framework, so any clarifications would be appreciated.

Based on the repo names (graphcool/graphcool-framework vs graphcool/prisma), I thought I should report here, even though this repo doesn't seem to have much attention (maybe it will soon?). Clarification about this would be appreciated as well. Thanks for your time and keep up the good work 🙂

**Comment by iamclaytonray** [comment]
Check out the docs [here](https://www.graph.cool/docs/reference/graphcool-cli/overview-zboghez5go/)

Maybe we can something like that in the quickstart?

**Comment by nikolasburk** [comment]
Thanks for opening this issue @sedubois! Since we released Prisma, usage of `graphcool-framework` is obsolete and the references have been removed everywhere! 🙌

**Comment by marktani** [comment]
If you have further questions refer to [this Forum thread](https://www.graph.cool/forum/t/graphcool-framework-and-prisma/2237?u=nilan) 🙂
