### ISSUE TITLE
Terminal command graphcool-framework not found

### ISSUE THREAD

**Issue by tini2n** [graphcool/graphcool-framework#2]
I installed `graphcool-framework` globally by npm. 
`npm install -g graphcool-framework`
Version is 0.11.5.

After installation I typed `graphcool-framework init server`
and get `-bash: graphcool-framework: command not found` error.

I think that problem might be with npm

**Comment by iamclaytonray** [comment]
Try:

`npm uninstall -g graphcool-framework`
`npm i -g graphcool-framework`

Copy/paste the output from npm on this issue

**Comment by iamclaytonray** [comment]
Also, what's your version of:

Node - `node -v`
NPM `npm -v`
OS

**Comment by tini2n** [comment]
Thanx! `npm: 5.3.0` `node: 8.6.0`

**Comment by iamclaytonray** [comment]
Okay. Try doing `yarn global add graphcool-framework`

**Comment by iamclaytonray** [comment]
Ahh... It looks like it could be a problem with your `$PATH`

Try running:

`npm root -g`

**Comment by iamclaytonray** [comment]
Typically, global libs/modules are installed into `/usr/local/lib/node_modules`

**Comment by tini2n** [comment]
Yarn install didn't help.
`npm root -g` return `/Users/tini2n/.npm-global/lib/node_modules`

**Comment by iamclaytonray** [comment]
Yeah, it's an issue with your `NODE_PATH`.

Try:

`npm i -g graphcool-framework --prefix /usr/local/lib/node_modules`

**Comment by iamclaytonray** [comment]
If that works, then we'll change your path so you can install global modules correctly

**Comment by tini2n** [comment]
Unfortunately it didn't help

**Comment by iamclaytonray** [comment]
Hmmm... What was the output?

**Comment by tini2n** [comment]
```
npm i -g graphcool-framework --prefix /usr/local/lib/node_modules

npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/lib/node_modules/bin/gcf -> /usr/local/lib/node_modules/lib/node_modules/graphcool-framework/dist/index.js
/usr/local/lib/node_modules/bin/graphcool-framework -> /usr/local/lib/node_modules/lib/node_modules/graphcool-framework/dist/index.js
+ graphcool-framework@0.11.5
updated 1 package in 10.558s
```

**Comment by iamclaytonray** [comment]
Try: `npm i -g graphcool-framework --prefix /usr/local/`

**Comment by iamclaytonray** [comment]
I'm honestly not sure. I'm almost positive it has to do with your path not being set correctly but I'm not 100% sure what the solution is

**Comment by tini2n** [comment]
worked! changing graphcool-framework path helped. just need `npm i -g graphcool-framework --prefix /usr/local/`. I am not sure, but looks like i need to change path for all global packages

**Comment by iamclaytonray** [comment]
Haha, awesome. Other global packages should continue to work but I suggest changing your root global path to `/usr/local/lib/node_modules/`. You can go ahead and close this issue. If you need more help, ping me in Slack
