### ISSUE TITLE
How to do GraphCool Deploy on ejected docker-compose.yml setup

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#455]
<a href="https://github.com/rohitghatol"><img src="https://avatars1.githubusercontent.com/u/899864?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rohitghatol](https://github.com/rohitghatol)**
_Wednesday Jan 10, 2018 at 07:36 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1568_

----

Graphcool has a feature called $>graphcool local eject , which provides us with a docker-compose.yml file.

Now lets say, I go to production with that docker-compose.yml file, add my docker image for node graphql microservice to that as well. And now everything runs fine.

Next Release, I introduce some fields or introduce a new type, and now I want to do data migration on graphcool docker image.

How do I do it? Does Graphcool Service (docker based) has end points for me to push a new graphql schema to that? Can Graphcool still connect to exported setup of graphcool?

**Comment by rohitghatol** [comment]
I could find the steps for following on prisma site 
1. run prismadb using docker-compose
2. and manage it using prisma cli

https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu

**Comment by marktani** [comment]
Thanks @rohitghatol 🙂
