### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Fallenstedt** [graphcool/graphcool-framework#496]
**Current behavior**
When I start a new project with `graphcool-framework init server` I get the following instructios

```
To get started, cd into the new directory:
  cd server

To deploy your Graphcool service:
  graphcool deploy

To start your local Graphcool cluster:
  graphcool local up

To add facebook authentication to your service:
  graphcool add-template auth/facebook
```
yet none of these commands works. 

**Reproduction**

1.  Start a new project with `graphcool-framework init server && cd server`
2. Type `graphcool deploy` # => command not found: graphcool

**Expected behavior?**

Any instructions in the upon starting a new project should be prefixed with `graphcool-framework` and not `graphcool`. Ex: `graphcool-framework deploy` is valid but `graphcool deploy` is not.

**Comment by marktani** [comment]
Please use the `graphcool` package instead: `npm install -g graphcool`.
Did you read to use `graphcool-framework` somewhere? We should update this resource.

**Comment by Fallenstedt** [comment]
@marktani 
Installing `graphcool` works on my other machine. 
However, when I type `graphcool -v` it prints: `graphcool-framework/0.11.5 (darwin-x64) node-v9.4.0`

I was instructed to use `graphcool-framework` from these tutorials: https://www.howtographql.com/angular-apollo/0-introduction/
