### ISSUE TITLE
`https://subscriptions.ap-northeast-1.graph.cool/v1/chatie: No 'Access-Control-Allow-Origin'`

### ISSUE THREAD

**Issue by zixia** [graphcool/graphcool-framework#504]
Hello,

I'm experiencing CORS problem when I first time using graphcool service in Angular. I got this: 

`Failed to load https://subscriptions.ap-northeast-1.graph.cool/v1/chatie: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I'm using apollo-client, Any idea?

**Comment by marktani** [comment]
This was resolved here: https://www.graph.cool/forum/t/cors-problem-no-access-control-allow-origin-header-is-present-in-the-subscriptions-endpoint/2988?u=nilan
