### ISSUE TITLE
Several problems cross continents

### ISSUE THREAD

**Issue by Kisepro** [graphcool/graphcool-framework#518]
Hi,

I'm figuring out that there are a lot of functionalities not working cross continents.
I'm working from Asia on a European server. ( But I already had the same working from Europe to an Asian server )

Problems already face because of the continents :
- Subscriptions 
- export data

I didn't tested if it was fixed or not.

What I have now : 
- permissions
- hook functions

# Permissions : 
I get the classic old problem message :  "Cannot query field 'SomeUserExists' on type 'Query'. "
See my last post on :  https://www.graph.cool/forum/t/testing-permission-queries/1661/29?u=aspro

# Hook functions : 
When I try to deploy a hook function like  
```
  cascadeDelete:
    type: operationBefore
    operation: Video.delete
    handler:
      code:
        src: src/video/onDeleteVideo.js
```
It ends up by getting the classical error message : "software.amazon.awssdk.services.lambda.model.CodeStorageExceededException: Code storage limit exceeded."

**Please**, assume that I can make **everything working** if I'm using the **current continent** where I'm working from.  Therefore it can't be a problem of my code, moreover I lost a lot of days investigating a lot of different solutions from internet before figure out it was related to the server's continent

I know the VPN can be a temporary solution but I don't want to have to pay a membership to a VPN service just to use graphcool.

**Comment by marktani** [comment]
Hey @Kisepro 👋 

1. subscriptions: I'm not aware of any problems here, can you point me to an issue report? Is this still a problem?
2. Export data: we're taking a look at this soon! See #456 
3. Permission Endpoint: Could you please create a new issue for this? 🙂
4. This is not a region-specific problem, please see #517 for more information and a workaround.

> Please, assume that I can make everything working if I'm using the current continent where I'm working from. 

Totally agreed!

>  Therefore it can't be a problem of my code, moreover I lost a lot of days investigating a lot of different solutions from internet before figure out it was related to the server's continent.

I'm sorry about the time you investigated! Feel free to reach out with questions if you are uncertain about something, that can sometimes be the quicker router 🙂

I'll close this issue, please create individual issues as I mentioned above 🙏
