### ISSUE TITLE
Broken link in the doc of the api gateway

### ISSUE THREAD

**Issue by cricrio** [graphcool/graphcool-framework#7]
The link to the api gateway example is broken.

Link to the markdown of doc : [here](https://github.com/graphcool/graphcool-framework/blob/master/docs/0.x/04-Reference/07-API-Gateway/01-Overview.md)

And the broken link : [broken link](https://github.com/graphcool/graphcool-framework/tree/master/examples/typescript-gateway-custom-schema)

**Comment by cricrio** [comment]
The link is also broken in README in the services examples section.

**Comment by marktani** [comment]
Thanks for reporting, @nikolasburk will take a look soon 🙂

**Comment by nikolasburk** [comment]
Hi @cricrio, thanks a lot for pointing this out! 🙏 We actually decided to remove the `API Gateway` chapter from the docs as it was outdated and not particularly relevant for the Graphcool Framework. Instead, I encourage you to take a look at the [GraphQL boilerplates](https://github.com/graphql-boilerplates) which combine `graphql-yoga` & Prisma to end up with a GraphQL API Gateway.
