### ISSUE TITLE
Single responsibility principle FTW

### ISSUE THREAD

**Issue by steida** [graphcool/graphcool-framework#8]
For the Love of God, choose one lib and deprecate the other. Why the developer would have to think about differences between graphcool and graphcool-framework.

Thank you :-)

**Comment by steida** [comment]
My suggestion:

Deprecate graphcool-framework CLI, let's use graphcool. Because `yarn graphcool ...`
Rename https://github.com/graphcool/graphcool-framework to https://github.com/graphcool/graphcool.

We have prisma, right? So why that -framework suffix?

**Comment by steida** [comment]
Remove all "framework" noise. There are only two services: 1) graphcool 2) prisma.

Do it please.

**Comment by schickling** [comment]
@nikolasburk is on it 🙌

**Comment by nikolasburk** [comment]
All references to `graphcool-framework` and `prisma-cli` in docs and websites have been cleaned up, thanks a lot for pushing for that @steida! 🙏

> I'm 99,99% sure I caught everything, in case you ever see another reference, feel free to ping me directly.
